# Generated by Django 2.0.5 on 2018-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('html', models.TextField()),
                ('errorno', models.TextField()),
                ('errormessage', models.TextField()),
            ],
        ),
    ]
